"""Rule-based agent.

Decision rule (paper eq. 1):
    Move to the free neighbour with highest food f_max if and only if
        f_max * alpha > f_h + e_i * ft
    where alpha is the risk-propensity gene, f_h is food in the current cell,
    e_i is current energy, and ft is the transfer fraction (movement cost).
    alpha < 1 encodes risk aversion, alpha = 1 a rational cost-benefit threshold,
    alpha > 1 risk seeking.
    Reproduction is controlled independently by the beta gene:
    reproduce with probability beta.
"""

import math
import random
from typing import List, Optional, Tuple

from config import ACTIONS, ALPHA_MAX, ALPHA_MIN, BETA_MAX, BETA_MIN, ModelParams
from .base import AgentBase


class RuleBasedAgent(AgentBase):

    def __init__(
        self,
        x: int,
        y: int,
        energy: float,
        alpha: float = 1.0,
        beta: float = -1.0,
        online_learning: bool = False,
        lr_alpha: float = 0.05,
        lr_beta: float = 0.05,
        baseline_alpha: float = 0.15,
        reward_clip: float = 2.0,
    ) -> None:
        super().__init__(x, y, energy)
        if alpha < 0:
            alpha = random.uniform(ALPHA_MIN, ALPHA_MAX)
        if beta < 0:
            beta = random.uniform(BETA_MIN, BETA_MAX)
        self.alpha = self._clamp(alpha)       # risk-propensity gene alpha
        self.beta = self._clamp_beta(beta)    # reproduction gene beta
        self.online_learning = online_learning
        self.lr_alpha = lr_alpha
        self.lr_beta = lr_beta
        self.baseline_alpha = baseline_alpha
        self.reward_clip = reward_clip
        # Separate EMA baselines for decomposed reward signals
        self._baseline_energy = 0.0
        self._baseline_fitness = 0.0
        self._last_valid_decision = False
        self._last_can_reproduce = True
        self._last_food_ratio = 1.0

    @staticmethod
    def _clamp(v: float) -> float:
        return max(ALPHA_MIN, min(ALPHA_MAX, v))

    @staticmethod
    def _clamp_beta(v: float) -> float:
        return max(BETA_MIN, min(BETA_MAX, v))

    def update_online(
        self,
        moved: bool,
        r_energy: float,
        r_fitness: float,
        should_reproduce: bool = False,
        valid_decision: bool = True,
        can_reproduce: bool = True,
        food_ratio: float = 1.0,
    ) -> None:
        """Adaptive threshold update with decomposed reward signals."""
        if not self.online_learning:
            return

        r_energy = max(-self.reward_clip, min(self.reward_clip, float(r_energy)))
        r_fitness = max(-self.reward_clip, min(self.reward_clip, float(r_fitness)))

        adv_energy = r_energy - self._baseline_energy
        self._baseline_energy = (
            (1.0 - self.baseline_alpha) * self._baseline_energy
            + self.baseline_alpha * r_energy
        )

        adv_fitness = r_fitness - self._baseline_fitness
        self._baseline_fitness = (
            (1.0 - self.baseline_alpha) * self._baseline_fitness
            + self.baseline_alpha * r_fitness
        )

        # Alpha: reward-modulated threshold adaptation. This is intentionally
        # described as a heuristic, not as an exact policy gradient, because
        # movement is generated by a deterministic threshold rule.
        # action_sign: +1 if moved (higher alpha promotes movement), -1 if stayed.
        # Sensitivity is highest close to the actual decision boundary
        # alpha * food_ratio = 1, where changing alpha can affect the policy.
        if valid_decision:
            action_sign = 1.0 if moved else -1.0
            boundary_margin = abs(self.alpha * food_ratio - 1.0)
            sensitivity = 1.0 / (1.0 + 4.0 * boundary_margin)
            self.alpha = self._clamp(
                self.alpha + self.lr_alpha * adv_energy * action_sign * sensitivity
            )

        # Beta: REINFORCE in logit space, gated on reproduction feasibility.
        # Only update when a free adjacent cell existed — otherwise the decision
        # had no possible effect and updating would inject noise.
        if can_reproduce:
            p_beta = self._clamp_beta(self.beta)
            p_safe_b = max(1e-9, min(1.0 - 1e-9, p_beta))
            logit_b = math.log(p_safe_b / (1.0 - p_safe_b))
            logit_b += self.lr_beta * adv_fitness * ((1.0 if should_reproduce else 0.0) - p_beta)
            self.beta = self._clamp_beta(1.0 / (1.0 + math.exp(-logit_b)))

    def decide_action(
        self, percept: List[float], params: ModelParams
    ) -> Tuple[int, int, bool]:
        food_neighbors = percept[:4]
        occ_neighbors = percept[4:8]
        food_here = percept[8]

        # Whether any adjacent cell is free (needed for beta feasibility gate)
        self._last_can_reproduce = any(occ < 0.5 for occ in occ_neighbors)

        best_idx: Optional[int] = None
        best_food: float = -1.0
        for i in range(4):
            if occ_neighbors[i] > 0.5:
                continue
            f = food_neighbors[i]
            if f > best_food or (f == best_food and random.random() < 0.5):
                best_food = f
                best_idx = i

        if best_idx is None:
            self._last_valid_decision = False
            self._last_food_ratio = 1.0
            return 0, 0, random.random() < self.beta

        transfer_cost = self.energy * params.transfer_fraction
        threshold = food_here + transfer_cost

        # food_ratio > 1: moving is profitable; < 1: staying is better
        self._last_food_ratio = best_food / max(threshold, 1e-6)

        if best_food > 0:
            ratio = threshold / best_food
            self._last_valid_decision = 0.01 < ratio < 1.99
        else:
            self._last_valid_decision = False

        if best_food * self.alpha > threshold:
            dx, dy = ACTIONS[best_idx]
            return dx, dy, random.random() < self.beta
        return 0, 0, random.random() < self.beta
